### ISSUE TITLE
Issues with latest update 2.26

### ISSUE THREAD

**Issue by Daveo7** [cr4ckp0t/ElvUI_SystemDatatext#5]
Set plugin to list only 5 add-ons in memory usage list, but it displays all add-ons in this list upto either the hardcoded maximum or the total number of add-ons I have running.

Left click for Garbage Collection does work. but nothing reported in chat.
Right click for Reload UI doesn't work

Looks like it's also ignoring the latency type to display. Shows World on Datatext instead of Home (as selected).

Tooltip show '(Modifier Click) Clear Garbage'.

[WoWScrnShot_071420_021338](https://user-images.githubusercontent.com/68258079/87369308-1a86a300-c578-11ea-93cc-05c2d7cb711c.jpg)

**Comment by cr4ckp0t** [comment]
I'm not sure what to tell you. I tested everything just now and it all works as it is supposed to. It sounds like your config is messed up and it's not reading it properly, since everything relating to the config is not working. Perhaps another addon is messing with it, I can't really speak to your particular setup.

**Comment by Daveo7** [comment]
Ok. V2.24 worked fine with ElvUI 11.41. This only started after upgrading to ElvUI 11.44 & SystemDatatext 2.26.

How do I reset the saved settings to get this working again?

**Comment by Daveo7** [comment]
Found the issue. I had 'System' selected as Datatext instead of 'System (Improved)'.

Sorry for the confusion.
